"""Few more changes

Revision ID: 717f04694e4e
Revises: 7ab9502cbaee
Create Date: 2026-03-10 10:12:01.432363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '717f04694e4e'
down_revision = '7ab9502cbaee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_queries',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start', sa.String(), nullable=False),
    sa.Column('end', sa.String(), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('chosen_route_rank', sa.Integer(), nullable=False),
    sa.Column('chosen_route_path', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('geometry', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lighting', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('greenery', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pollution', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('surface_quality', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pub_distance', sa.Float(), nullable=False))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('information', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('in_use', sa.Boolean(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('x_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)
        batch_op.alter_column('y_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)
        batch_op.alter_column('feature',
               existing_type=postgresql.ENUM('CROSSING', 'TRAFFIC_LIGHT', 'TURNING_CIRCLE', name='highwayfeatures'),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('feature',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CROSSING', 'TRAFFIC_LIGHT', 'TURNING_CIRCLE', name='highwayfeatures'),
               existing_nullable=True)
        batch_op.alter_column('y_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('x_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('in_use')
        batch_op.drop_column('information')

    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_column('pub_distance')
        batch_op.drop_column('surface_quality')
        batch_op.drop_column('pollution')
        batch_op.drop_column('greenery')
        batch_op.drop_column('lighting')
        batch_op.drop_column('geometry')
        batch_op.drop_column('access_score')

    op.drop_table('route_queries')
    # ### end Alembic commands ###
