"""Added in table for changelog

Revision ID: 7ab9502cbaee
Revises: f8ad5f13a0b5
Create Date: 2026-03-02 00:30:41.494374

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7ab9502cbaee'
down_revision = 'f8ad5f13a0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_change_log',
    sa.Column('change_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('x_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)
        batch_op.alter_column('y_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('y_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('x_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('database_change_log')
    # ### end Alembic commands ###
