"""Added in tables for node, edge, location, mission, mission_progress

Revision ID: c30181648a41
Revises: a70b3f6d3193
Create Date: 2026-02-03 15:44:26.318203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30181648a41'
down_revision = 'a70b3f6d3193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the enum type exists before using it in batch_alter_table.
    user_access_enum = sa.Enum('TRAVELLERS', 'ADMINS', 'MAINTAINERS', name='useraccesstype')
    bind = op.get_bind()
    user_access_enum.create(bind, checkfirst=True)

    op.create_table('missions',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('mission_name', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('EASY', 'MEDIUM', 'HARD', name='missiontier'), nullable=False),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('x_coordinate', sa.Float(precision=15), nullable=False),
    sa.Column('y_coordinate', sa.Float(precision=15), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('edges',
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('travel_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('role', user_access_enum, nullable=False))
        batch_op.drop_column('first_name')
        batch_op.drop_column('id')
        batch_op.drop_column('last_name')
        batch_op.create_primary_key('pk_user_account', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_constraint('pk_user_account', type_='primary')
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('user_id')
        batch_op.create_primary_key('user_account_pkey', ['id'])

    op.drop_table('edges')
    op.drop_table('nodes')
    op.drop_table('missions')
    bind = op.get_bind()
    sa.Enum('TRAVELLERS', 'ADMINS', 'MAINTAINERS', name='useraccesstype').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
