"""Final changes

Revision ID: e13c6d21ecaa
Revises: e1a9f6b2c4d1
Create Date: 2026-03-23 11:15:45.904639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13c6d21ecaa'
down_revision = 'e1a9f6b2c4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accessible', sa.Boolean(), nullable=True))

    with op.batch_alter_table('graph_presets', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)

    with op.batch_alter_table('mission_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chosenAnswer', sa.String(), nullable=False))

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('x_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)
        batch_op.alter_column('y_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('y_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('x_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('mission_progress', schema=None) as batch_op:
        batch_op.drop_column('chosenAnswer')

    with op.batch_alter_table('graph_presets', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_column('is_accessible')

    # ### end Alembic commands ###
