"""Added new tables

Revision ID: f8ad5f13a0b5
Revises: c30181648a41
Create Date: 2026-02-15 23:02:21.085943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8ad5f13a0b5'
down_revision = 'c30181648a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    highwayfeatures_enum = sa.Enum(
        'CROSSING',
        'TRAFFIC_LIGHT',
        'TURNING_CIRCLE',
        name='highwayfeatures',
    )
    highwayfeatures_enum.create(bind, checkfirst=True)

    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('DRINKING_AREA', 'BUS_STOP', 'GENERAL_AMENITY', name='locationtype'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('mission_progress',
    sa.Column('mission_progress_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='missionstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('mission_progress_id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.alter_column('from_node_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('to_node_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('possible_answers', sa.String(), nullable=False))

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature', sa.Enum('CROSSING', 'TRAFFIC_LIGHT', 'TURNING_CIRCLE', name='highwayfeatures'), nullable=True))
        batch_op.alter_column('node_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('x_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)
        batch_op.alter_column('y_coordinate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('y_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('x_coordinate',
               existing_type=sa.Float(precision=15),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('node_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('feature')

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('possible_answers')

    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.alter_column('to_node_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('from_node_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('mission_progress')
    op.drop_table('locations')
    bind = op.get_bind()
    sa.Enum('CROSSING', 'TRAFFIC_LIGHT', 'TURNING_CIRCLE', name='highwayfeatures').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
